version: "3.8"
services:
  db:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=saskq@Pasa@#s25s@54
      - MONGO_INITDB_DATABASE=easy-generator--task
